name: camp_leader
description: Camp leader management app prototype
version: 1.0.0
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  go_router: ^6.0.0
  flutter_local_notifications: ^9.0.0
  firebase_core: ^2.4.1
  cloud_firestore: ^4.5.0
  sentry_flutter: ^7.11.1
  connectivity_plus: ^4.0.0
  pdf: ^3.10.4
  firebase_storage: ^11.0.16
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
