name: camp_leader
description: Camp leader management app prototype
version: 1.0.0
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  go_router: ^16.0.0
  flutter_local_notifications: ^19.4.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  sentry_flutter: ^9.6.0
  connectivity_plus: ^6.1.4
  pdf: ^3.10.4
  firebase_storage: ^13.0.0
  fl_chart: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_cloud_firestore: ^4.0.0
flutter:
  uses-material-design: true
